### PR TITLE
Add encoding support

### PR DESCRIPTION
**Pull request by codesftdev**
Add support to get the raw bytes (what is saved to the .bsor) from a Bsor class instance

### CODE REVIEW

**Comment by codesftdev** [comment]
Scoring seemed to be incomplete, though is fine

**Comment by Schippi** [comment]
you changed calc_cut_score for some reason and it doesnt behave the way it used to

**Comment by codesftdev** [comment]
will look into

**Comment by codesftdev** [comment]
after closer inspection, looks like the way the encoder tries to get the instances is broken
closing for now

**Pull request closed without merging**
